jwt :
  accessKey : 45124589562312457845134679461312
  refreshKey : 13462356794613462356897946132346

spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/memberdb?UseUnicode=true&serverTimezone=Asia/Seoul
    username : root
    password: fpdlswj365
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
       mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: 127.0.0.1
    port: 6379

  dog:
    profile:
      image:
        upload: /Users/choiseonjae/Desktop/PetApp/profiles
    post:
      image:
        upload: /Users/choiseonjae/Desktop/PetApp/posts
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb+srv://chltjswo:fpdlswj365@mycluster.zzoydp8.mongodb.net/chat?retryWrites=true&w=majority&appName=myCluster
